os:
  - linux

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - libgmp-dev
      - libbz2-dev
      - libssh-dev
      - openssl
      - openssh-server
      - python3

script:
    - pip3 install pycrypto
    - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
    - export CC=/usr/bin/gcc-6
    - export CXX=/usr/bin/g++-6
    - gcc -v && g++ -v && cmake --version
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cd Test/test
    - ctest -VV
    - cd ../..
    - cp ../finalize.sh finalize.sh
    - sh finalize.sh
