os:
  - linux
  - osx

language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - libgmp-dev
      - libbz2-dev
      - libssh-dev
      - openssl
      - openssh-server
      - python3

script:
    - gcc -v && g++ -v && cmake --version
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cd Test/test
    - ctest -VV
    - cd ../..
    - cp ../finalize.sh finalize.sh
    - sh finalize.sh
